docs:
  image:
    repository: cqmirdevops.azurecr.io/cq-devops-azurescope
    tag: latest
    pullPolicy: IfNotPresent

  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 8888

  replicaCount: 1

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/whitelist-source-range: "172.26.0.0/16,172.27.0.0/16,172.25.0.0/16,172.16.101.0/24,211.177.23.90/32,221.141.114.84/32,58.120.29.19/32,211.177.23.91/32,221.141.114.92/32,221.141.114.99/32,61.40.226.242/32"
    hosts:
      - host: cq-devops-azscope.mironline.co.kr
        paths:
          - path: /
            pathType: Prefix
      - host: cq-devops-azscope.mironline.co.kr
        paths:
          - path: /
            pathType: Prefix
    tls:
      enabled: true
      secretName: mironline-tls
      hosts:
        - cq-devops-azscope.mironline.co.kr